using System.Collections.Generic;

namespace OutSystems.NssFormatCurrency;

/// <summary>
/// Interface generated by Integration Studio for the FormatCurrency extension.
/// Matches the XIF action signatures.
/// </summary>
public interface IssFormatCurrency
{
    /// <summary>
    /// Formats the Decimal based on the Locale provided.
    /// </summary>
    void MssGetCurrencyFormattedByLocale(
        string  ssLocale,
        decimal ssDecimal,
        bool    ssHasCurrency,
        string  ssCurrency,
        bool    ssUseNativeDigits,
        bool    ssUseChineseExtendedNumbers,
        bool    ssUseFinancialChinese,
        out string ssFormattedText);

    /// <summary>
    /// Gets the C# supported Locales and their parametrizations.
    /// </summary>
    void MssGetLocales(out List<RecLocale> ssListOfLocales);

    /// <summary>
    /// Converts a Locale Decimal String into a valid Decimal.
    /// </summary>
    void MssGetDecimalFromLocaleDecimalString(
        string  ssInputLocaleDecimalString,
        string  ssLocale,
        string  ssCurrency,
        out bool    ssIsValidDecimal,
        out int     ssErrorMessageCode,
        out string  ssErrorMessage,
        out decimal ssDecimal);
}
