namespace OutSystems.NssFormatCurrency;

/// <summary>
/// Maps to the Locale Structure defined in Integration Studio.
/// Field names use the ss-prefix convention generated by Integration Studio.
/// </summary>
public struct RecLocale
{
    public string ssName;
    public string ssRFC4646;
    public string ssCurrencyDecimalDigits;
    public string ssCurrencyDecimalSeparator;
    public string ssCurrencyGroupSeparator;
    public string ssCurrencyGroupSizes;
    public string ssCurrencyNegativePattern;
    public string ssCurrencyPositivePattern;
    public string ssNegativeSign;
    public string ssCurrencySymbol;
    public string ssNativeDigits;
}
